=== gematik/ePA-XDS-Document/src/implementation_guides/ig-schema-definition.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$ref": "#/definitions/StructureDefinition",
	"$version": "1.2.2",
	"definitions": {
		"CardinalityDefinition": {
			"description": "Constraints on the amount of the XDS folder or document in order to support that structured document in the electronic health record system.",
			"type": "object",
			"properties": {
				"min": {
					"type": "string"
				},
				"max": {
					"type": "string"
				},
				"unique": {
					"description": "The value 'true' means that solely one document/folder with the availability status 'approved' is allowed to be registered with the given metadata combination. False means that multiple instances may be submitted.",
					"type": "boolean"
				}
			},
			"required": [
				"min",
				"max"
			],
			"additionalProperties": false
		},
		"FolderDefinition": {
			"type": "object",
			"properties": {
				"name": {
					"type": "string"
				},
				"value": {
					"anyOf": [
						{
							"title": "value",
							"type": "object",
							"properties": {
								"code": {
									"type": "string"
								},
								"codeSystem": {
									"type": "string"
								},
								"displayName": {
									"type": "string"
								},
								"deprecatedFrom": {
									"description": "The following value is deprecated and should not be used from this date on. Useage of alternative value with same name instead is recommended",
									"type": "string",
									"format": "date"
								},
								"desc": {
									"$ref": "#/definitions/DescriptionDefinition"
								}
							},
							"required": [
								"code",
								"codeSystem",
								"displayName"
							],
							"additionalProperties": false
						},
						{
							"title": "value",
							"type": "array",
							"items": {
								"type": "object",
								"properties": {
									"code": {
										"type": "string"
									},
									"codeSystem": {
										"type": "string"
									},
									"displayName": {
										"type": "string"
									},
									"deprecatedFrom": {
										"description": "The following value is deprecated and should not be used from this date on. Usage of alternative value with same name instead is recommended.",
										"type": "string",
										"format": "date"
									},
									"desc": {
										"$ref": "#/definitions/DescriptionDefinition"
									}
								},
								"required": [
									"code",
									"codeSystem",
									"displayName"
								],
								"additionalProperties": false
							}
						},
						{
							"title": "value",
							"type": "array",
							"items": {
								"type": "string"
							}
						}
					]
				}
			},
			"required": [
				"name",
				"value"
			],
			"additionalProperties": false
		},
		"DescriptionDefinition": {
			"title": "desc",
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"language": {
						"type": "string"
					},
					"#text": {
						"type": "string"
					}
				},
				"required": [
					"language",
					"#text"
				],
				"additionalProperties": false
			}
		},
		"DocumentDefinition": {
			"type": "object",
			"properties": {
				"version": {
					"description": "The version of the document format.",
					"type": "string"
				},
				"name": {
					"description": "The name of the specific document.",
					"type": "string"
				},
				"description": {
					"description": "The description of the specific document.",
					"type": "string"
				},
				"canonicalUrl": {
					"description": "A canonical URL of the structure definiton of the specific document.",
					"type": "string"
				},
				"metadata": {
					"title": "metadata",
					"type": "array",
					"items": {
						"$ref": "#/definitions/FolderDefinition"
					}
				},
				"documentCardinality": {
					"$ref": "#/definitions/CardinalityDefinition"
				},
				"implementationArtifact": {
					"description": "This usage specification is not intended for verifying structured documents.",
					"type": "boolean"
				},
				"maxDocumentHistory": {
					"description": "Defines the maximum amount of deprecated elements to be kept in a XDS RPLC chain (approved document does not count). Oldest entries may be deleted when this limit gets exeeded",
					"type": "integer"
				}
			},
			"required": [
				"name",
				"description",
				"metadata",
				"documentCardinality"
			],
			"additionalProperties": false
		},
		"StructureDefinition": {
			"type": "object",
			"properties": {
				"name": {
					"description": "The technical name of the structured document.",
					"type": "string"
				},
				"description": {
					"description": "The overall description of the structured document.",
					"type": "string"
				},
				"igVersion": {
					"description": "Version information of the Implementation Guideline file",
					"type": "string"
				},
				"guidelineDefinition": {
					"description": "A link to the (FHIR) implementation guideline including its version.",
					"type": "object",
					"properties": {
						"url": {
							"type": "string",
							"format": "uri"
						},
						"version": {
							"type": "string"
						}
					},
					"required": [
						"url"
					],
					"additionalProperties": false
				},
				"folderCardinality": {
					"$ref": "#/definitions/CardinalityDefinition"
				},
				"validFromDate": {
					"description": "Date from which the structured document is accepted (upload/download) by ePA-server.",
					"type": "string",
					"format": "date"
				},
				"clientReadOnlyFromDate": {
					"description": "Date from which the structured document is accepted (only download) by ePA-server. The upload is rejected by ePA-server",
					"type": "string",
					"format": "date"
				},
				"type": {
					"description": "The collection type of the structured document - either 'mixed' or 'uniform'.",
					"type": "string"
				},
				"metadata": {
					"$ref": "#/definitions/FolderDefinition"
				},
				"elements": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/DocumentDefinition"
					}
				}
			},
			"required": [
				"name",
				"description",
				"guidelineDefinition",
				"validFromDate",
				"elements"
			]
		}
	}
}

=== gematik/ePA-XDS-Document/src/implementation_guides/ig-eab.json
{
	"name": "Discharge Letter",
	"description": "Discharge Letter defined by KBV acc. to § 383 SGB V",
	"igVersion": "3.0.1",
	"guidelineDefinition": {
		"url": "https://www.kbv.de/media/sp/RL-eArztbrief.pdf"
	},
	"folderCardinality": {
		"min": "1",
		"max": "1",
		"unique": true
	},
	"validFromDate": "2021-06-15",
	"metadata": {
		"name": "folder.codeList",
		"value": {
			"code": "eab",
			"codeSystem": "1.2.276.0.76.5.512",
			"displayName": "eArztbrief",
			"desc": [
				{
					"language": "de-DE",
					"#text": "Daten in elektronischen Briefen zwischen den an der Versorgung der Versicherten teilnehmenden Ärzten und Einrichtungen (elektronische Arztbriefe)"
				}
			]
		}
	},
	"elements": [
		{
			"name": "eArztbrief",
			"description": "This document is a CDA-based discharge letter bundled in an XML container (cf. container definition in PHR_Common.xsd).",
			"canonicalUrl": "https://wiki.hl7.de/index.php?title=IG:Arztbrief_2006",
			"metadata": [
				{
					"name": "documentEntry.classCode",
					"value": {
						"code": "BRI",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.8",
						"displayName": "Brief",
						"desc": [
							{
								"language": "de-DE",
								"#text": "Alle Varianten von Arztbriefen wie Überweisungsbrief, Entlassbrief, etc. sowie weitere zusammenfassende Dokumente mit einer ärztlichen oder pflegerischen Bewertung der Fakten. Befundberichte werden über das Konzept \"BEF\" (Befundbericht) abgedeckt."
							}
						]
					}
				},
				{
					"name": "documentEntry.typeCode",
					"value": {
						"code": "BERI",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.9",
						"displayName": "Arztberichte",
						"desc": [
							{
								"language": "de-DE",
								"#text": "Ärztliche Zusammenfassungen und Verlaufsbeurteilungen von Behandlungsepisoden, Epikrisen und Abschlussberichte zu stationären oder ambulanten Behandlungsfällen. Beispiele: Arztbrief, Entlassungsbericht, Ärztliche Stellungnahme, Durchgangsarztbericht / BG-Bericht, Rehabericht, Verlegungsbericht, vorläufiger Arztbericht, ärztlicher Verlaufsbericht, Ambulanzbericht"
							}
						]
					}
				},
				{
					"name": "documentEntry.formatCode",
					"value": {
						"code": "urn:gematik:ig:Arztbrief:r3.1",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.6",
						"displayName": "Arztbrief § 291f SGB V"
					}
				},
				{
					"name": "documentEntry.eventCodeList",
					"value": {
						"code": "ED110104",
						"codeSystem": "1.2.276.0.76.5.552",
						"displayName": "eArztbrief"
					}
				},				
				{
					"name": "documentEntry.mimeType",
					"value": [
						"application/xml"
					]
				}
			],
			"documentCardinality": {
				"min": "0",
				"max": "n"
			}
		}
	]
}

=== gematik/ePA-XDS-Document/src/implementation_guides/ig-mothersrecord.json
{
	"name": "Maternity Records",
	"description": "Maternity Records defined as a medical information object (MIO) by KBV.",
	"igVersion": "3.0.1",
	"guidelineDefinition": {
		"url": "https://mio.kbv.de/display/MP1X0",
		"version": "1.0.0"
	},
	"folderCardinality": {
		"min": "0",
		"max": "n",
		"unique": false
	},
	"validFromDate": "2021-05-05",
	"clientReadOnlyFromDate": "2026-04-01",
	"type": "uniform",
	"metadata": {
		"name": "folder.codeList",
		"value": {
			"code": "pregnancy_childbirth",
			"codeSystem": "1.2.276.0.76.5.512",
			"displayName": "Schwangerschaft und Geburt",
			"desc": [
				{
					"language": "de-DE",
					"#text": "Daten gemäß der nach § 92 Absatz 1 Satz 2 Nummer 4 in Verbindung mit den §§ 24c bis 24f beschlossenen Richtlinie des Gemeinsamen Bundesausschusses über die ärztliche Betreuung während der Schwangerschaft und nach der Entbindung (elektronischer Mutterpass) sowie Daten, die sich aus der Versorgung der Versicherten mit Hebammenhilfe ergeben."
				}
			]
		}
	},
	"elements": [
		{
			"version": "1.0.0",
			"name": "KBV_PR_MIO_MR_Bundle",
			"description": "This document is of FHIR resource type KBV_PR_MIO_MR_Bundle.",
			"canonicalUrl": "https://fhir.kbv.de/StructureDefinition/KBV_PR_MIO_MR_Bundle",
			"metadata": [
				{
					"name": "documentEntry.classCode",
					"value": {
						"code": "AUS",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.8",
						"displayName": "Medizinischer Ausweis",
						"desc": [
							{
								"language": "de-DE",
								"#text": "Ausweise, Pässe und ähnliche kurze Datensätze, die wichtige medizinische Informationen zusammenfassen. Beispiele: Allergiepass, Allergieausweis, Impfpass, Impfausweis, Impfbuch, Notfalldatensatz"
							}
						]
					}
				},
				{
					"name": "documentEntry.typeCode",
					"value": {
						"code": "GEBU",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.9",
						"displayName": "Schwangerschafts- und Geburtsdokumentation",
						"desc": [
							{
								"language": "de-DE",
								"#text": "Dokumente mit allen Informationen über die Phase vor, während und nach dem Geburtsverlauf, inklusive Funktionsdiagnostik (z.B. CTG) und Bildgebende Diagnostik und ähnliche Befunde die sich auf das Kind beziehen. Weiterhin beinhalten das Konzept Belege zur Neugeborenversorgung, wenn sie der Akte der Mutter zugeordnet sind. Verordnungen und Medikamentationsdokumentation hingegen werden über die jeweiligen Konzepte (VERO und MEDI) abgebildet. Beispiele: Geburtenbericht, Geburtenprotokoll, Geburtenverlaufskurve, Neugeborenenscreening, Partogramm, Wiegekarte, Neugeborenendokumentationsbogen, Säuglingskurve, Stillprotokoll"
							}
						]
					}
				},
				{
					"name": "documentEntry.formatCode",
					"value": {
						"code": "urn:gematik:ig:Mutterpass:v1.0.0",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.6",
						"displayName": "Mutterpass (gematik)"
					}
				},
				{
					"name": "documentEntry.mimeType",
					"value": [
						"application/fhir+xml",
						"application/pkcs7-mime"
					]
				}
			],
			"documentCardinality": {
				"min": "0",
				"max": "n"
			}
		}
	]
}

=== gematik/ePA-XDS-Document/src/implementation_guides/ig-medical-image.json
{
	"name": "Medical Image",
	"description": "Usage specification for registering medical images in the PHR (former requirement A_17540). The codes below are taken from DICOM Part 16, Context Group 29 'Acquisition Modality' (Value Set 1.2.840.10008.6.1.19).",
	"igVersion": "3.0.1",
	"guidelineDefinition": {
		"url": "https://fachportal.gematik.de/"
	},
	"validFromDate": "2023-01-01",
	"clientReadOnlyFromDate": "2027-10-20",
	"elements": [
		{
			"name": "Medical Image",
			"description": "This document is a medical image.",
			"metadata": [
				{
					"name": "documentEntry.classCode",
					"value": {
						"code": "BIL",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.8",
						"displayName": "Bilddaten",
						"desc": [
							{
								"language": "de-DE",
								"#text": "Unter diesem Konzept werden alle Dokumente zusammengefasst, deren Ziel es ist, einen Sachverhalt optisch darzustellen. Beispiele sind Röntgen-, MRT-, CT-Aufnahmen oder Fotos von Wunden, Körperteilen oder ähnlichem. Bilder von Textdokumenten werden nach dem enthaltenen Text klassiert, Videodokumente unter Videodaten."
							}
						]
					}
				},
				{
					"name": "documentEntry.eventCodeList",
					"value": [
					   {
						"code": "BDUS",
						"codeSystem": "1.2.840.10008.2.16.4",
						"displayName": "Ultrasound Bone Densitometry"
					   },
					   {
						"code": "BMD",
						"codeSystem": "1.2.840.10008.2.16.4",
						"displayName": "Bone Mineral Densitometry"
					   },
					   {
						"code": "CR",
						"codeSystem": "1.2.840.10008.2.16.4",
						"displayName": "Computed Radiography"
					   },
					   {
						"code": "CT",
						"codeSystem": "1.2.840.10008.2.16.4",
						"displayName": "Computed Tomography"
					   },
					   {
						"code": "DX",
						"codeSystem": "1.2.840.10008.2.16.4",
						"displayName": "Digital Radiography"
					   },
					   {
						"code": "ES",
						"codeSystem": "1.2.840.10008.2.16.4",
						"displayName": "Endoscopy"
					   },
					   {
						"code": "GM",
						"codeSystem": "1.2.840.10008.2.16.4",
						"displayName": "General Microscopy"
					   },
					   {
						"code": "IO",
						"codeSystem": "1.2.840.10008.2.16.4",
						"displayName": "Intra-oral Radiography"
					   },
					   {
						"code": "IVOCT",
						"codeSystem": "1.2.840.10008.2.16.4",
						"displayName": "Intravascular Optical Coherence Tomography"
					   },
					   {
						"code": "IVUS",
						"codeSystem": "1.2.840.10008.2.16.4",
						"displayName": "Intravascular Ultrasound"
					   },
					   {
						"code": "MG",
						"codeSystem": "1.2.840.10008.2.16.4",
						"displayName": "Mammography"
					   },
					   {
						"code": "MR",
						"codeSystem": "1.2.840.10008.2.16.4",
						"displayName": "Magnetic Resonance"
					   },
					   {
						"code": "NM",
						"codeSystem": "1.2.840.10008.2.16.4",
						"displayName": "Nuclear Medicine"
					   },
					   {
						"code": "OCT",
						"codeSystem": "1.2.840.10008.2.16.4",
						"displayName": "Optical Coherence Tomography"
					   },
					   {
						"code": "OP",
						"codeSystem": "1.2.840.10008.2.16.4",
						"displayName": "Ophthalmic Photography"
					   },
					   {
						"code": "OPT",
						"codeSystem": "1.2.840.10008.2.16.4",
						"displayName": "Ophthalmic Tomography"
					   },
					   {
						"code": "OPTENF",
						"codeSystem": "1.2.840.10008.2.16.4",
						"displayName": "Ophthalmic Tomography En Face"
					   },
					   {
						"code": "PT",
						"codeSystem": "1.2.840.10008.2.16.4",
						"displayName": "Positron Emission Tomography"
					   },
					   {
						"code": "PX",
						"codeSystem": "1.2.840.10008.2.16.4",
						"displayName": "Panoramic X-Ray"
					   },
					   {
						"code": "RF",
						"codeSystem": "1.2.840.10008.2.16.4",
						"displayName": "Radiofluoroscopy"
					   },
					   {
						"code": "RG",
						"codeSystem": "1.2.840.10008.2.16.4",
						"displayName": "Radiographic Imaging"
					   },
					   {
						"code": "SM",
						"codeSystem": "1.2.840.10008.2.16.4",
						"displayName": "Slide Microscopy"
					   },
					   {
						"code": "US",
						"codeSystem": "1.2.840.10008.2.16.4",
						"displayName": "Ultrasound"
					   },
					   {
						"code": "XA",
						"codeSystem": "1.2.840.10008.2.16.4",
						"displayName": "X-Ray Angiography"
					   },
					   {
						"code": "XC",
						"codeSystem": "1.2.840.10008.2.16.4",
						"displayName": "External-camera Photography"
					   }
					]
				},
				{
					"name": "documentEntry.mimeType",
					"value": [
						"application/pdf"
					]
				}
			],
			"documentCardinality": {
				"min": "0",
				"max": "n"
			},
			"implementationArtifact": true
		}
	]
}
