=== gematik/ePA-XDS-Document/src/implementation_guides/ig-schema-definition.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$ref": "#/definitions/StructureDefinition",
	"$version": "1.2.2",
	"definitions": {
		"CardinalityDefinition": {
			"description": "Constraints on the amount of the XDS folder or document in order to support that structured document in the electronic health record system.",
			"type": "object",
			"properties": {
				"min": {
					"type": "string"
				},
				"max": {
					"type": "string"
				},
				"unique": {
					"description": "The value 'true' means that solely one document/folder with the availability status 'approved' is allowed to be registered with the given metadata combination. False means that multiple instances may be submitted.",
					"type": "boolean"
				}
			},
			"required": [
				"min",
				"max"
			],
			"additionalProperties": false
		},
		"FolderDefinition": {
			"type": "object",
			"properties": {
				"name": {
					"type": "string"
				},
				"value": {
					"anyOf": [
						{
							"title": "value",
							"type": "object",
							"properties": {
								"code": {
									"type": "string"
								},
								"codeSystem": {
									"type": "string"
								},
								"displayName": {
									"type": "string"
								},
								"deprecatedFrom": {
									"description": "The following value is deprecated and should not be used from this date on. Useage of alternative value with same name instead is recommended",
									"type": "string",
									"format": "date"
								},
								"desc": {
									"$ref": "#/definitions/DescriptionDefinition"
								}
							},
							"required": [
								"code",
								"codeSystem",
								"displayName"
							],
							"additionalProperties": false
						},
						{
							"title": "value",
							"type": "array",
							"items": {
								"type": "object",
								"properties": {
									"code": {
										"type": "string"
									},
									"codeSystem": {
										"type": "string"
									},
									"displayName": {
										"type": "string"
									},
									"deprecatedFrom": {
										"description": "The following value is deprecated and should not be used from this date on. Usage of alternative value with same name instead is recommended.",
										"type": "string",
										"format": "date"
									},
									"desc": {
										"$ref": "#/definitions/DescriptionDefinition"
									}
								},
								"required": [
									"code",
									"codeSystem",
									"displayName"
								],
								"additionalProperties": false
							}
						},
						{
							"title": "value",
							"type": "array",
							"items": {
								"type": "string"
							}
						}
					]
				}
			},
			"required": [
				"name",
				"value"
			],
			"additionalProperties": false
		},
		"DescriptionDefinition": {
			"title": "desc",
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"language": {
						"type": "string"
					},
					"#text": {
						"type": "string"
					}
				},
				"required": [
					"language",
					"#text"
				],
				"additionalProperties": false
			}
		},
		"DocumentDefinition": {
			"type": "object",
			"properties": {
				"version": {
					"description": "The version of the document format.",
					"type": "string"
				},
				"name": {
					"description": "The name of the specific document.",
					"type": "string"
				},
				"description": {
					"description": "The description of the specific document.",
					"type": "string"
				},
				"canonicalUrl": {
					"description": "A canonical URL of the structure definiton of the specific document.",
					"type": "string"
				},
				"metadata": {
					"title": "metadata",
					"type": "array",
					"items": {
						"$ref": "#/definitions/FolderDefinition"
					}
				},
				"documentCardinality": {
					"$ref": "#/definitions/CardinalityDefinition"
				},
				"implementationArtifact": {
					"description": "This usage specification is not intended for verifying structured documents.",
					"type": "boolean"
				},
				"maxDocumentHistory": {
					"description": "Defines the maximum amount of deprecated elements to be kept in a XDS RPLC chain (approved document does not count). Oldest entries may be deleted when this limit gets exeeded",
					"type": "integer"
				}
			},
			"required": [
				"name",
				"description",
				"metadata",
				"documentCardinality"
			],
			"additionalProperties": false
		},
		"StructureDefinition": {
			"type": "object",
			"properties": {
				"name": {
					"description": "The technical name of the structured document.",
					"type": "string"
				},
				"description": {
					"description": "The overall description of the structured document.",
					"type": "string"
				},
				"igVersion": {
					"description": "Version information of the Implementation Guideline file",
					"type": "string"
				},
				"guidelineDefinition": {
					"description": "A link to the (FHIR) implementation guideline including its version.",
					"type": "object",
					"properties": {
						"url": {
							"type": "string",
							"format": "uri"
						},
						"version": {
							"type": "string"
						}
					},
					"required": [
						"url"
					],
					"additionalProperties": false
				},
				"folderCardinality": {
					"$ref": "#/definitions/CardinalityDefinition"
				},
				"validFromDate": {
					"description": "Date from which the structured document is accepted (upload/download) by ePA-server.",
					"type": "string",
					"format": "date"
				},
				"clientReadOnlyFromDate": {
					"description": "Date from which the structured document is accepted (only download) by ePA-server. The upload is rejected by ePA-server",
					"type": "string",
					"format": "date"
				},
				"type": {
					"description": "The collection type of the structured document - either 'mixed' or 'uniform'.",
					"type": "string"
				},
				"metadata": {
					"$ref": "#/definitions/FolderDefinition"
				},
				"elements": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/DocumentDefinition"
					}
				}
			},
			"required": [
				"name",
				"description",
				"guidelineDefinition",
				"validFromDate",
				"elements"
			]
		}
	}
}

=== gematik/ePA-XDS-Document/src/implementation_guides/ig-dmp_cr_V_1.json
{
	"name": "eDMP-Datensatz Rückenschmerz",
	"description": "Indikationsspezifischer Datensatz für das strukturierte Behandlungsprogramm Rückenschmerz",
	"igVersion": "3.0.0",
	"guidelineDefinition": {
		"url": "https://update.kbv.de/ita-update/Medizinische-Dokumentationen/Rueckenschmerz/"
	},
	"folderCardinality": {
		"min": "1",
		"max": "1",
		"unique": true
	},
	"validFromDate": "2023-01-01",
	"clientReadOnlyFromDate": "2027-10-20",
	"metadata": {
		"name": "folder.codeList",
		"value": {
			"code": "other",
			"codeSystem": "1.2.276.0.76.5.512",
			"displayName": "in andere Kategorien nicht einzuordnende Dokumente, eDMPs sowie Telemedizinisches Monitoring",
			"desc": [
				{
					"language": "de-DE",
					"#text": "sonstige von den Leistungserbringern für den Versicherten bereitgestellte Daten, insbesondere Daten, die sich aus der Teilnahme des Versicherten an strukturierten Behandlungsprogrammen bei chronischen Krankheiten gemäß § 137f ergeben"
				}
			]
		}
	},
	"elements": [
		{
			"name": "eDMP record for chronic back pain",
			"description": "This document is an HL7 CDA-based document.",
			"metadata": [
				{
					"name": "documentEntry.classCode",
					"value": {
						"code": "BRI",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.8",
						"displayName": "Brief",
						"desc": [
							{
								"language": "de-DE",
								"#text": "Alle Varianten von Arztbriefen wie Überweisungsbrief, Entlassbrief, etc. sowie weitere zusammenfassende Dokumente mit einer ärztlichen oder pflegerischen Bewertung der Fakten. Befundberichte werden über das Konzept BEF (Befundbericht) abgedeckt"
							}
						]
					}
				},
				{
					"name": "documentEntry.typeCode",
					"value": {
						"code": "FPRO",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.9",
						"displayName": "Therapiedokumentation",
						"desc": [
							{
								"language": "de-DE",
								"#text": "Dokumentation zur Durchführung von Therapien, durch ärztliche und nicht-ärztliche Therapeuten. Auch die zugehörigen Therapieanforderungen werden mit diesem Konzept abgebildet. Bei fachspezifischen Dokumententypen wie Bestrahlungsprotokollen, sollte stattdessen das spezifischere Konzept verwendet werden, z.B. BSTR (Bestrahlungsdokumentation), OPDK (OP-Dokumente). Reine Dokumentation der Medikation wird durch das Konzept MEDI (Medikamentöse Therapien) abgebildet. Beispiele: Ergotherapieprotokoll, Logopädieprotokoll, Physiotherapieprotokoll, Schmerztherapieprotokoll, Reanimationsprotokoll, Dialysedokumente, Psychotherapeutische Dokumente"
							}
						]
					}
				},
				{
					"name": "documentEntry.formatCode",
					"value": {
						"code": "urn:gematik:ig:DMP-Rueckenschmerz:v1",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.6",
						"displayName": "eDMP Rückenschmerz (gematik)"
					}
				},
				{
					"name": "documentEntry.eventCodeList",
					"value": {
						"code": "09",
						"codeSystem": "1.2.276.0.76.5.223",
						"displayName": "Rueckenschmerz"
					}
				},
				{
					"name": "documentEntry.mimeType",
					"value": [
						"application/hl7-v3"
					]
				}
			],
			"documentCardinality": {
				"min": "0",
				"max": "n"
			}
		}
	]
}

=== gematik/ePA-XDS-Document/src/implementation_guides/ig-emp.json
{
	"name": "Medication Plan",
	"description": "Medication plan defined by gematik (cf. [gemSpec_Info_AMTS] and [https://github.com/gematik/api-telematik/tree/OPB5/fa/amtss/])",
	"igVersion": "3.1.2",
	"guidelineDefinition": {
		"url": "https://fachportal.gematik.de/fileadmin/Fachportal/Downloadcenter/Releases/TI-Baseline/Spezifikationen_Release_TI-Baseline_2022-1.zip",
		"version": "1.6.0"
	},
	"folderCardinality": {
		"min": "1",
		"max": "1",
		"unique": true
	},
	"validFromDate": "2021-06-15",
	"clientReadOnlyFromDate": "2026-12-31",
	"metadata": {
		"name": "folder.codeList",
		"value": {
			"code": "emp",
			"codeSystem": "1.2.276.0.76.5.512",
			"displayName": "Elektronischer Medikationsplan",
			"desc": [
				{
					"language": "de-DE",
					"#text": "Daten des elektronischen Medikationsplans nach § 334 Absatz 1 Satz 2 Nummer 4"
				}
			]
		}
	},
	"elements": [
		{
			"name": "Medication Plan",
			"description": "This document is an XML-based document in UKF-encoding.",
			"metadata": [
				{
					"name": "documentEntry.classCode",
					"value": {
						"code": "PLA",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.8",
						"displayName": "Planungsdokument",
						"desc": [
							{
								"language": "de-DE",
								"#text": "Dokumente zur Behandlungsplanung (z.B. Bestrahlungsplan, Medikationsplan) oder Versorgungsplanung (z.B. Nachsorge-Plan). Weitere Beispiele: Wiedereingliederungsplan."
							}
						]
					}
				},
				{
					"name": "documentEntry.typeCode",
					"value": {
						"code": "MEDI",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.9",
						"displayName": "Medikamentöse Therapien",
						"desc": [
							{
								"language": "de-DE",
								"#text": "Therapieprotokolle zum Nachweis der Verabreichung oder Verordnung von Arzneimitteln. Beispiele: Medikamentenplan, Chemotherapieprotokoll, Hormontherapieprotokoll, Apothekenbuch, Rezept, Anforderung Medikation"
							}
						]
					}
				},
				{
					"name": "documentEntry.formatCode",
					"value": {
						"code": "urn:gematik:ig:Medikationsplan:r3.1",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.6",
						"displayName": "Medikationsplan (gematik)"
					}
				},
				{
					"name": "documentEntry.mimeType",
					"value": [
						"application/xml"
					]
				}
			],
			"documentCardinality": {
				"min": "0",
				"max": "1"
			}
		}
	]
}

=== gematik/ePA-XDS-Document/src/implementation_guides/ig-dentalrecord.json
{
	"name": "Dental Records",
	"description": "Dental records defined as a medical information object (MIO) by KBV.",
	"igVersion": "3.0.1",
	"guidelineDefinition": {
		"url": "https://mio.kbv.de/display/ZB1X1X0",
		"version": "1.1.0"
	},
	"folderCardinality": {
		"min": "1",
		"max": "1",
		"unique": true
	},
	"validFromDate": "2021-05-05",
	"clientReadOnlyFromDate": "2027-10-20",
	"type": "uniform",
	"metadata": {
		"name": "folder.codeList",
		"value": {
			"code": "dental",
			"codeSystem": "1.2.276.0.76.5.512",
			"displayName": "Zahnärztliche Dokumentation",
			"desc": [
				{
					"language": "de-DE",
					"#text": "Daten aus der zahnärztlichen Dokumentation"
				}
			]
		}
	},
	"elements": [
		{
			"version": "1.1.0",
			"name": "KBV_PR_MIO_ZAEB_Bundle",
			"description": "This document is a dental record.",
			"canonicalUrl": "https://fhir.kbv.de/StructureDefinition/KBV_PR_MIO_ZAEB_Bundle",
			"metadata": [
				{
					"name": "documentEntry.classCode",
					"value": {
						"code": "AUS",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.8",
						"displayName": "Medizinischer Ausweis",
						"desc": [
							{
								"language": "de-DE",
								"#text": "Ausweise, Pässe und ähnliche kurze Datensätze, die wichtige medizinische Informationen zusammenfassen. Beispiele: Allergiepass, Allergieausweis, Impfpass, Impfausweis, Impfbuch, Notfalldatensatz"
							}
						]
					}
				},
				{
					"name": "documentEntry.typeCode",
					"value": [
						{
						"code": "PATD",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.9",
						"displayName": "Patienteneigene Dokumente",
						"deprecatedFrom": "2023-01-01",
						"desc": [
							{
								"language": "de-DE",
								"#text": "Dokumente, welche der Patient zu seinem Kontakt in der Gesundheitseinrichtung mitbringt, die aber nicht in unmittelbarem Zusammenhang mit dem aktuellen Kontakt stehen müssen. Sowie Dokumente, in denen das mitgebrachte Patienteneigentum festgehalten wird. Beispiele: Ausweise, Vorsorgevollmacht, Patientenverfügung, Wertgegenständeverwaltung, Notfalldatensatz, Patiententagebuch"
							}
						]
						},
						{
						"code": "ABRE",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.9",
						"displayName": "Abrechnungsdokumente",
						"desc": [
							{
								"language": "de-DE",
								"#text": "Administrative Dokumente, die die Abrechnung eines Patientenfalles betreffen. Medizinische Dokumentation, die als Grundlage für die Abrechnung oder als Begründung für die Behandlung herangezogen wird, ist mit dem entsprechenden Konzept abzubilden. Einwilligungen zur Datenweitergabe an Abrechnungsstellen usw. werden mit dem Konzept EINW (\"Einwilligungen/Aufklärungen\") abgebildet. Der nicht abrechnungsbezogene Schriftwechsel mit der Krankenkasse wird mit dem Konzept SCHR (\"Schriftwechsel (administrativ)\") abgebildet. Beispiele: Abrechnungsschein, Rechnung ambulante/stationäre Behandlung, Kostenübernahmeverlängerung"
							}
						]
						}
					]
				},
				{
					"name": "documentEntry.formatCode",
					"value": {
						"code": "urn:gematik:ig:Zahnbonusheft:v1.1.0",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.6",
						"displayName": "Zahnbonusheft (gematik)"
					}
				},
				{
					"name": "documentEntry.mimeType",
					"value": [
						"application/fhir+xml",
						"application/pkcs7-mime"
					]
				}
			],
			"documentCardinality": {
				"min": "0",
				"max": "n"
			}
		}
	]
}

=== gematik/ePA-XDS-Document/src/implementation_guides/ig-eau_V_1_1.json
{
	"name": "Incapacity to Work Certificate Version 1.1",
	"description": "Nach § 73 Absatz 2 Satz 1 Nummer 9 ausgestellte Bescheinigung über eine Arbeitsunfähigkeit",
	"igVersion": "3.0.1",
	"guidelineDefinition": {
		"url": "https://simplifier.net/packages/kbv.ita.eau/1.1.1/",
		"version": "1.1.1"
	},
	"folderCardinality": {
		"min": "1",
		"max": "1",
		"unique": true
	},
	"validFromDate": "2023-07-01",
	"metadata": {
		"name": "folder.codeList",
		"value": {
			"code": "eau",
			"codeSystem": "1.2.276.0.76.5.512",
			"displayName": "Elektronische Arbeitsunfähigkeitsbescheinigungen",
			"desc": [
				{
					"language": "de-DE",
					"#text": "Nach § 73 Absatz 2 Satz 1 Nummer 9 ausgestellte Bescheinigung über eine Arbeitsunfähigkeit"
				}
			]
		}
	},
	"elements": [
		{
			"name": "Incapacity to Work Certificate",
			"description": "This document is an XML-based document.",
			"metadata": [
				{
					"name": "documentEntry.classCode",
					"value": {
						"code": "ADM",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.8",
						"displayName": "Administratives Dokument",
						"desc": [
							{
								"language": "de-DE",
								"#text": "Anträge, Aufklärung, Bescheinigungen; auch juristische Dokumente, Vereinbarungen und Verträge; Anmeldungen, Regelungen, Einwilligungen, Bestellungen, Rechnungen, Bescheide, Anordnungen (im juristischen Sinne), Aufträge, Ausweise (außer medizinische Ausweise wie Impfpässe, siehe Konzept AUS (\"Medizinischer Ausweis\")), Meldungen, Qualitätssicherungsdokumente, Patientenverfügungen"
							}
						]
					}
				},
				{
					"name": "documentEntry.typeCode",
					"value": {
						"code": "BESC",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.9",
						"displayName": "Ärztliche Bescheinigungen",
						"desc": [
							{
								"language": "de-DE",
								"#text": "Bestätigung eines Arztes über einen bestimmten, patientenbezogenen Sachverhalt. Beispiele: Arbeitsunfähigkeitsbescheinigung, Beurlaubung, Todesbescheinigung, Ärztliche Bescheinigung, Notfall-/ Vertretungsschein"
							}
						]
					}
				},
				{
					"name": "documentEntry.formatCode",
					"value": {
						"code": "urn:gematik:ig:Arbeitsunfaehigkeitsbescheinigung:v1.1",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.6",
						"displayName": "Arbeitsunfähigkeitsbescheinigung (gematik) v1.1"
					}
				},
				{
					"name": "documentEntry.mimeType",
					"value": [
						"application/fhir+xml",
						"application/pkcs7-mime"
					]
				}
			],
			"documentCardinality": {
				"min": "0",
				"max": "n"
			}
		}
	]
}

=== gematik/ePA-XDS-Document/src/implementation_guides/ig-epka_V_1_0.json
{
	"name": "Patient Summary",
	"description": "Patient summary defined as a medical information object (MIO) by KBV.",
	"igVersion": "1.0.2",
	"guidelineDefinition": {
		"url": "https://mio.kbv.de/display/PKA1X0X0",
		"version": "1.0.0"
	},
	"folderCardinality": {
		"min": "1",
		"max": "1",
		"unique": true
	},
	"validFromDate": "2025-07-15",
	"clientReadOnlyFromDate": "2027-10-20",
	"metadata": {
		"name": "folder.codeList",
		"value": {
			"code": "emergency",
			"codeSystem": "1.2.276.0.76.5.512",
			"displayName": "Notfalldaten",
			"desc": [
				{
					"language": "de-DE",
					"#text": "Daten der elektronischen Notfalldaten nach § 334 Absatz 1 Satz 2 Nummer 5 und 7"
				}
			]
		}
	},
	"elements": [
		{
			"version": "1.0.0",
			"name": "KBV_PR_MIO_NFDxDPE_Bundle",
			"description": "This document is of FHIR resource type KBV_PR_MIO_NFDxDPE_Bundle.",
			"canonicalUrl": "https://fhir.kbv.de/StructureDefinition/KBV_PR_MIO_NFDxDPE_Bundle",
			"metadata": [
				{
					"name": "documentEntry.classCode",
					"value": {
						"code": "AUS",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.8",
						"displayName": "Medizinischer Ausweis",
						"desc": [
							{
								"language": "de-DE",
								"#text": "Ausweise, Pässe und ähnliche kurze Datensätze, die wichtige medizinische Informationen zusammenfassen. Beispiele: Allergiepass, Allergieausweis, Impfpass, Impfausweis, Impfbuch, Notfalldatensatz"
							}
						]
					}
				},
				{
					"name": "documentEntry.typeCode",
					"value": {
						"code": "BEFU",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.9",
						"displayName": "Ergebnisse Diagnostik",
						"desc": [
							{
								"language": "de-DE",
								"#text": "Dokumentation zur Planung und Durchführung von Radiotherapien, einschließlich der ausgefüllten Anamnese- und Aufklärungsbögen zur Bestrahlungstherapie.Beispiele: Bestrahlungsplan, Bestrahlungsprotokoll, Bestrahlungsverordnung, Radiojodtherapieprotokoll, Therapieprotokoll mit Radionukleiden, Brachytherapieprotokoll, Bericht zur interventionellen Radioonkologie"
							}
						]
					}
				},
				{
					"name": "documentEntry.formatCode",
					"value": {
						"code": "urn:gematik:ig:pka:v1.0",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.6",
						"displayName": "Patientenkurzakte (gematik) v1.0"
					}
				},
				{
					"name": "documentEntry.mimeType",
					"value": [
						"application/fhir+xml"
					]
				}
			],
			"documentCardinality": {
				"min": "0",
				"max": "1"
			}
		}
	]
}

=== gematik/ePA-XDS-Document/src/implementation_guides/ig-childsrecord.json
{
	"name": "Child Medical Records",
	"description": "Child medical records defined as a medical information object (MIO) by KBV. It may include participation card and parental notes.",
	"igVersion": "3.0.1",
	"guidelineDefinition": {
		"url": "https://mio.kbv.de/display/UH1X0/U-Heft",
		"version": "1.1.0"
	},
	"folderCardinality": {
		"min": "1",
		"max": "1",
		"unique": true
	},
	"validFromDate": "2021-05-05",
	"clientReadOnlyFromDate": "2026-04-01",
	"type": "mixed",
	"metadata": {
		"name": "folder.codeList",
		"value": {
			"code": "child",
			"codeSystem": "1.2.276.0.76.5.512",
			"displayName": "Kinderuntersuchungsheft",
			"desc": [
				{
					"language": "de-DE",
					"#text": "Daten gemäß der nach § 92 Absatz 1 Satz 2 Nummer 3 und Absatz 4 in Verbindung mit § 26 beschlossenen Richtlinie des Gemeinsamen Bundesausschusses zur Früherkennung von Krankheiten bei Kindern (elektronisches Untersuchungsheft für Kinder)"
				}
			]
		}
	},
	"elements": [
		{
			"version": "1.0.0",
			"name": "KBV_PR_MIO_CMR_Bundle",
			"description": "This document is a child medical record.",
			"canonicalUrl": "https://fhir.kbv.de/StructureDefinition/KBV_PR_MIO_CMR_Bundle",
			"metadata": [
				{
					"name": "documentEntry.classCode",
					"value": {
						"code": "AUS",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.8",
						"displayName": "Medizinischer Ausweis",
						"desc": [
							{
								"language": "de-DE",
								"#text": "Ausweise, Pässe und ähnliche kurze Datensätze, die wichtige medizinische Informationen zusammenfassen. Beispiele: Allergiepass, Allergieausweis, Impfpass, Impfausweis, Impfbuch, Notfalldatensatz"
							}
						]
					}
				},
				{
					"name": "documentEntry.typeCode",
					"value": {
						"code": "BERI",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.9",
						"displayName": "Arztberichte",
						"desc": [
							{
								"language": "de-DE",
								"#text": "Ärztliche Zusammenfassungen und Verlaufsbeurteilungen von Behandlungsepisoden, Epikrisen und Abschlussberichte zu stationären oder ambulanten Behandlungsfällen. Beispiele: Arztbrief, Entlassungsbericht, Ärztliche Stellungnahme, Durchgangsarztbericht / BG-Bericht, Rehabericht, Verlegungsbericht, vorläufiger Arztbericht, ärztlicher Verlaufsbericht, Ambulanzbericht"
							}
						]
					}
				},
				{
					"name": "documentEntry.formatCode",
					"value": {
						"code": "urn:gematik:ig:KinderuntersuchungsheftUntersuchungen:v1.0.0",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.6",
						"displayName": "Untersuchungen Kinderuntersuchungsheft"
					}
				},
				{
					"name": "documentEntry.mimeType",
					"value": [
						"application/fhir+xml",
						"application/pkcs7-mime"
					]
				}
			],
			"documentCardinality": {
				"min": "0",
				"max": "n",
				"unique": false
			}
		},
		{
			"version": "1.0.0",
			"name": "KBV_PR_MIO_PC_Bundle",
			"description": "This document is a participation card.",
			"canonicalUrl": "https://fhir.kbv.de/StructureDefinition/KBV_PR_MIO_PC_Bundle",
			"metadata": [
				{
					"name": "documentEntry.classCode",
					"value": {
						"code": "AUS",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.8",
						"displayName": "Medizinischer Ausweis",
						"desc": [
							{
								"language": "de-DE",
								"#text": "Ausweise, Pässe und ähnliche kurze Datensätze, die wichtige medizinische Informationen zusammenfassen. Beispiele: Allergiepass, Allergieausweis, Impfpass, Impfausweis, Impfbuch, Notfalldatensatz"
							}
						]
					}
				},
				{
					"name": "documentEntry.typeCode",
					"value": {
						"code": "BESC",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.9",
						"displayName": "Ärztliche Bescheinigungen",
						"desc": [
							{
								"language": "de-DE",
								"#text": "Bestätigung eines Arztes über einen bestimmten, patientenbezogenen Sachverhalt. Beispiele: Arbeitsunfähigkeitsbescheinigung, Beurlaubung, Todesbescheinigung, Ärztliche Bescheinigung, Notfall-/ Vertretungsschein"
							}
						]
					}
				},
				{
					"name": "documentEntry.formatCode",
					"value": {
						"code": "urn:gematik:ig:KinderuntersuchungsheftTeilnahmekarte:v1.0.0",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.6",
						"displayName": "Teilnahmekarte Kinderuntersuchungsheft"
					}
				},
				{
					"name": "documentEntry.mimeType",
					"value": [
						"application/fhir+xml",
						"application/pkcs7-mime"
					]
				}
			],
			"documentCardinality": {
				"min": "0",
				"max": "n",
				"unique": false
			}
		},
		{
			"version": "1.0.0",
			"name": "KBV_PR_MIO_PN_Bundle",
			"description": "This document holds parental notes.",
			"canonicalUrl": "https://fhir.kbv.de/StructureDefinition/KBV_PR_MIO_PN_Bundle",
			"metadata": [
				{
					"name": "documentEntry.classCode",
					"value": {
						"code": "AUS",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.8",
						"displayName": "Medizinischer Ausweis",
						"desc": [
							{
								"language": "de-DE",
								"#text": "Ausweise, Pässe und ähnliche kurze Datensätze, die wichtige medizinische Informationen zusammenfassen. Beispiele: Allergiepass, Allergieausweis, Impfpass, Impfausweis, Impfbuch, Notfalldatensatz"
							}
						]
					}
				},
				{
					"name": "documentEntry.typeCode",
					"value": {
						"code": "PATD",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.9",
						"displayName": "Patienteneigene Dokumente",
						"desc": [
							{
								"language": "de-DE",
								"#text": "Dokumente, welche der Patient zu seinem Kontakt in der Gesundheitseinrichtung mitbringt, die aber nicht in unmittelbarem Zusammenhang mit dem aktuellen Kontakt stehen müssen. Sowie Dokumente, in denen das mitgebrachte Patienteneigentum festgehalten wird. Beispiele: Ausweise, Vorsorgevollmacht, Patientenverfügung, Wertgegenständeverwaltung, Notfalldatensatz, Patiententagebuch"
							}
						]
					}
				},
				{
					"name": "documentEntry.formatCode",
					"value": {
						"code": "urn:gematik:ig:KinderuntersuchungsheftNotizen:v1.0.0",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.6",
						"displayName": "Notizen Kinderuntersuchungsheft"
					}
				},
				{
					"name": "documentEntry.mimeType",
					"value": [
						"application/fhir+xml"
					]
				}
			],
			"documentCardinality": {
				"min": "0",
				"max": "n"
			}
		}
	]
}

=== gematik/ePA-XDS-Document/src/implementation_guides/ig-vaccination.json
{
	"name": "Vaccination Records",
	"description": "Vaccination records defined as a medical information object (MIO) by KBV.",
	"igVersion": "3.0.0",
	"guidelineDefinition": {
		"url": "https://mio.kbv.de/display/IM1X1X0",
		"version": "1.1.0"
	},
	"folderCardinality": {
		"min": "1",
		"max": "1",
		"unique": true
	},
	"validFromDate": "2021-05-05",
	"clientReadOnlyFromDate": "2027-10-20",
	"type": "uniform",
	"metadata": {
		"name": "folder.codeList",
		"value": {
			"code": "vaccination",
			"codeSystem": "1.2.276.0.76.5.512",
			"displayName": "Impfpass",
			"desc": [
				{
					"language": "de-DE",
					"#text": "Daten der Impfdokumentation nach § 22 des Infektionsschutzgesetzes (elektronische Impfdokumentation)"
				}
			]
		}
	},
	"elements": [
		{
			"version": "1.1.0",
			"name": "KBV_PR_MIO_Vaccination_Bundle_Entry",
			"description": "This document is a vaccination record and describes one or more given vaccinations.",
			"canonicalUrl": "https://fhir.kbv.de/StructureDefinition/KBV_PR_MIO_Vaccination_Bundle_Entry",
			"metadata": [
				{
					"name": "documentEntry.classCode",
					"value": {
						"code": "AUS",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.8",
						"displayName": "Medizinischer Ausweis",
						"desc": [
							{
								"language": "de-DE",
								"#text": "Ausweise, Pässe und ähnliche kurze Datensätze, die wichtige medizinische Informationen zusammenfassen. Beispiele: Allergiepass, Allergieausweis, Impfpass, Impfausweis, Impfbuch, Notfalldatensatz"
							}
						]
					}
				},
				{
					"name": "documentEntry.typeCode",
					"value": {
						"code": "MEDI",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.9",
						"displayName": "Medikamentöse Therapien",
						"desc": [
							{
								"language": "de-DE",
								"#text": "Therapieprotokolle zum Nachweis der Verabreichung oder Verordnung von Arzneimitteln. Beispiele: Medikamentenplan, Chemotherapieprotokoll, Hormontherapieprotokoll, Apothekenbuch, Rezept, Anforderung Medikation"
							}
						]
					}
				},
				{
					"name": "documentEntry.formatCode",
					"value": {
						"code": "urn:gematik:ig:Impfausweis:v1.1.0",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.6",
						"displayName": "Impfausweis (gematik)"
					}
				},
				{
					"name": "documentEntry.mimeType",
					"value": [
						"application/fhir+xml",
						"application/pkcs7-mime"
					]
				}
			],
			"documentCardinality": {
				"min": "0",
				"max": "n"
			}
		}
	]
}
